- name: Clean OpenStack deployment
  hosts: "{{ target_host | default('localhost') }}"
  tasks:
    - name: Cleanup openstack deployment
      ansible.builtin.include_role:
        name: cleanup_openstack
