# This task file detaches the BMH (Bare Metal Host) resources to prevent deprovisioning them
---
- name: Skip deprovision for BMH
  when: cifmw_deploy_bmh_bm_hosts_list | length > 0
  block:
    - name: Patch bmh with detached
      kubernetes.core.k8s:
        kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
        api_key: "{{ cifmw_openshift_token | default(omit)}}"
        context: "{{ cifmw_openshift_context | default(omit)}}"
        state: patched
        wait: true
        wait_timeout: 600
        api_version: metal3.io/v1alpha1
        kind: BareMetalHost
        namespace: "{{ cifmw_deploy_bmh_namespace }}"
        name: "{{ item }}"
        definition:
          metadata:
            annotations:
              baremetalhost.metal3.io/detached: ""
      loop: "{{ cifmw_deploy_bmh_bm_hosts_list }}"
      loop_control:
        label: "{{ item }}"

    - name: Wait for operationalStatus to become detached
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
        api_key: "{{ cifmw_openshift_token | default(omit)}}"
        context: "{{ cifmw_openshift_context | default(omit)}}"
        namespace: "{{ cifmw_deploy_bmh_namespace }}"
        kind: BareMetalHost
        api_version: metal3.io/v1alpha1
        name: "{{ item }}"
      retries: 60
      delay: 10
      until:
        - bmh_status.resources | length == 0 or bmh_status.resources[0].status.operationalStatus == 'detached'
      register: bmh_status
      loop: "{{ cifmw_deploy_bmh_bm_hosts_list }}"
      loop_control:
        label: "{{ item }}"
